### ISSUE TITLE
contract tests broken

### ISSUE THREAD

**Issue by jdar** [Imaginea/lms#111]
Let's do this "good news/bad news" style.

GOOD NEWS:
The app javascript tests (jest tests, 'npm run test')  are passing. Hooray!

BAD NEWS:
However, the command 'truffle test' (solidity tests) fail for me. (even after trying a bunch of different versions of Node, testrpc, and truffle)

Here is the test output. Superficial googling suggests the culprit might be some change in the Solidity language, but I can't find any version combinations of dependencies that work together.

I include a Dockerfile below that output, for replicability.

I am also curious if this project's structure is still considered a good example. If it is not, can you recommend a better example project to illustrate upgradeability? Thank you. (I do understand that 3 months is an eon in ethereum coding.)

Best,
Darius

truffle contract tests:
 9 passing (2s)
  2 pending
  2 failing

  1) Contract: Organisation "before each" hook for "should add the member":
     Error: VM Exception while processing transaction: invalid JUMP at 4865d8177e6363219d40076a909b1c1bf06aa3ebaca71d5508e445c4bdd3836a/0e2fc852338b960375576b7b9d64d7d5bb78ecbc:5311
      at Object.InvalidResponse (node_modules/truffle-contract/node_modules/web3/lib/web3/errors.js:35:16)
      at node_modules/truffle-contract/node_modules/web3/lib/web3/requestmanager.js:86:36
      at XMLHttpRequest.request.onreadystatechange (node_modules/web3/lib/web3/httpprovider.js:118:13)
      at XMLHttpRequestEventTarget.dispatchEvent (node_modules/xhr2/lib/xhr2.js:64:18)
      at XMLHttpRequest._setReadyState (node_modules/xhr2/lib/xhr2.js:354:12)
      at XMLHttpRequest._onHttpResponseEnd (node_modules/xhr2/lib/xhr2.js:509:12)
      at IncomingMessage.<anonymous> (node_modules/xhr2/lib/xhr2.js:469:24)
      at endReadableNT (_stream_readable.js:1047:12)

  2) Contract: MembersLibrary "before each" hook for "should fetch the number of members added to app":
     Error: VM Exception while processing transaction: invalid JUMP at 562f35d7b006a97dba260842287fe0e774d182beefd4d65bff76f0b34dacd198/1cca692d938d6f9f5170d6192619c68a88cfe244:1775
      at Object.InvalidResponse (node_modules/truffle-contract/node_modules/web3/lib/web3/errors.js:35:16)
      at node_modules/truffle-contract/node_modules/web3/lib/web3/requestmanager.js:86:36
      at XMLHttpRequest.request.onreadystatechange (node_modules/web3/lib/web3/httpprovider.js:118:13)
      at XMLHttpRequestEventTarget.dispatchEvent (node_modules/xhr2/lib/xhr2.js:64:18)
      at XMLHttpRequest._setReadyState (node_modules/xhr2/lib/xhr2.js:354:12)
      at XMLHttpRequest._onHttpResponseEnd (node_modules/xhr2/lib/xhr2.js:509:12)
      at IncomingMessage.<anonymous> (node_modules/xhr2/lib/xhr2.js:469:24)
      at endReadableNT (_stream_readable.js:1047:12)

FROM node:8.1.3
RUN git clone https://github.com/Imaginea/lms  /lms

WORKDIR /lms

RUN npm install
RUN npm install truffle@3.1.10
RUN npm install ethereumjs-testrpc@4.1.0
RUN ./node_modules/.bin/truffle compile
RUN npm run build
ENTRYPOINT /bin/bash
# to test:
# "./node_modules/.bin/testrpc &"
# and then "./node_modules/.bin/truffle test"

**Comment by inovizz** [comment]
@jdar thanks for notifying this issue, we are aware of it and it shall be fixed soon. I'll keep you posted.

**Comment by neeldhwaj** [comment]
@jdar The issue has been taken care by [PR#112](https://github.com/Imaginea/lms/pull/112). Hence, I'm closing this issue.
